name: CI

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore:
      - '**.md' # Ignores all Markdown files
  pull_request:
    branches: [ "master", "develop" ]
    paths-ignore:
      - '**.md' # Ignores all Markdown files

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Configure git for tests
      run: |
        git config --global user.name "Test User"
        git config --global user.email "test@example.com"

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
      
    - name: Test examples compile and run
      run: |
        echo "Testing examples..."
        for example in examples/*.rs; do
          example_name=$(basename "$example" .rs)
          echo "Building example: $example_name"
          cargo build --example "$example_name"
        done
