name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1 # Or actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable # Use 'stable' to get the latest stable Rust
        profile: minimal
        override: true

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
